<?php

/**
 * Implementation of hook_file_url_alter().
 */
function imce_pressflow_file_url_alter(&$path) {
  if ($path != '')
    return;

  switch (variable_get('file_downloads', FILE_DOWNLOADS_PUBLIC)) {
    case FILE_DOWNLOADS_PUBLIC:
      $path = $GLOBALS['base_url'] .'/'. file_directory_path() .'/'. str_replace('\\', '/', $path);
      break;
    case FILE_DOWNLOADS_PRIVATE:
      $path = url('system/files/'. $path, array('absolute' => TRUE));
      break;
  }
}
